name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat ./package.json
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: cat ./package.json
      - run: git config --global user.email "tungpt260794@gmail.com"
      - run: git config --global user.name "tungpt260794"
      - run: npm version patch
      - run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
